/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mydocument.views;

import static aplicativo.DocumentaciondeAyuda.ShowJPanel;
import java.awt.Color;

/**
 *
 * @author Jhonatan
 */
public class incendioysale extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public incendioysale() {
        initComponents();
        InitStyle();
    }
    
    private void InitStyle(){
        title.putClientProperty("FlatLaf.Style", "font: bold $h3.regular.font");
        title.setForeground(Color.black);
        jLabel10.putClientProperty("FlatLaf.styleClass", "large");
        jLabel10.setForeground(Color.black);
        jLabel12.putClientProperty("FlatLaf.styleClass", "large");
        jLabel12.setForeground(Color.black);
        jLabel11.putClientProperty("FlatLaf.styleClass", "large");
        jLabel11.setForeground(Color.black);
        jLabel14.putClientProperty("FlatLaf.styleClass", "large");
        jLabel14.setForeground(Color.black);
        jLabel15.putClientProperty("FlatLaf.styleClass", "large");
        jLabel15.setForeground(Color.black);
        jLabel16.putClientProperty("FlatLaf.styleClass", "large");
        jLabel16.setForeground(Color.black);
        jLabel18.putClientProperty("FlatLaf.styleClass", "large");
        jLabel18.setForeground(Color.black);
        jLabel2.putClientProperty("FlatLaf.styleClass", "large");
        jLabel2.setForeground(Color.black);
        jLabel4.putClientProperty("FlatLaf.styleClass", "large");
        jLabel4.setForeground(Color.black);
        jLabel5.putClientProperty("FlatLaf.styleClass", "large");
        jLabel5.setForeground(Color.black);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(542, 444));
        setMinimumSize(new java.awt.Dimension(542, 444));
        setPreferredSize(new java.awt.Dimension(542, 444));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(320, 360));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("la nariz y la boca  arrastrándote por el piso.");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel11.setText("cuanto puedas. ");
        background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel12.setText(" impedir el paso del  humo.");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 190, -1));

        jLabel14.setText("2.Pon trapos mojados en las rendijas de la puerta para");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel15.setText("3.Llama a los servicios de emergencia al teléfono 911 en ");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel16.setText("1.Protéjete del fuego cerrando todas las puertas que puedas");
        background.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel18.setText("4.Tápate con un trapo o pañuelo, de preferencia húmedo,");
        background.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/incendio y salir (1).jpg"))); // NOI18N
        background.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 202, 420));

        title.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        title.setText("SI HAY UN INCENDIO EN TU CASA Y NO PUEDES SALIR");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 320, 30));

        jLabel2.setText("5.Si no puedes bajar, intenta subir hasta la azotea; deja ");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel4.setText("abierta la puerta  de acceso a la misma para que el humo no");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel5.setText("se acumule en el cubo de las  escaleras.");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ShowJPanel(new incendio());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
