/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicativo;

import com.mydocument.views.*;
import com.mydocument.views.Principal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author Jhonatan
 */
public class DocumentaciondeAyuda extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    public DocumentaciondeAyuda() {
        initComponents();
        SetDate();
        InitContent();
        InitStyles();
    }
    
    private void InitStyles(){
         lbl_apartado.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        lbl_apartado.setForeground(Color.white);
        lbl_introdocu.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        lbl_introdocu.setForeground(Color.white);
        dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        dateText.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new javax.swing.JPanel();
        panel_apartado = new javax.swing.JPanel();
        lbl_apartado = new javax.swing.JLabel();
        btm_docurobocasa = new javax.swing.JButton();
        btm_docuprincipal = new javax.swing.JButton();
        btm_docuincendio = new javax.swing.JButton();
        btm_docuemergencia = new javax.swing.JButton();
        btm_docuasalto = new javax.swing.JButton();
        btm_docuvolver = new javax.swing.JButton();
        panel_mensajeinicio = new javax.swing.JPanel();
        lbl_introdocu = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(590, 486));

        panel_background.setBackground(new java.awt.Color(255, 255, 255));

        panel_apartado.setBackground(new java.awt.Color(255, 0, 0));

        lbl_apartado.setBackground(new java.awt.Color(255, 51, 51));
        lbl_apartado.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_apartado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apartado.setText("APARTADO");

        btm_docurobocasa.setBackground(new java.awt.Color(255, 51, 51));
        btm_docurobocasa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btm_docurobocasa.setForeground(new java.awt.Color(255, 255, 255));
        btm_docurobocasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/robo de cas(1).jpg"))); // NOI18N
        btm_docurobocasa.setText("¿Que hacer en un robo de casa?");
        btm_docurobocasa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        btm_docurobocasa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btm_docurobocasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docurobocasaActionPerformed(evt);
            }
        });

        btm_docuprincipal.setBackground(new java.awt.Color(255, 51, 51));
        btm_docuprincipal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btm_docuprincipal.setForeground(new java.awt.Color(255, 255, 255));
        btm_docuprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/principal (1).png"))); // NOI18N
        btm_docuprincipal.setText("Principal");
        btm_docuprincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        btm_docuprincipal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btm_docuprincipal.setIconTextGap(10);
        btm_docuprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docuprincipalActionPerformed(evt);
            }
        });

        btm_docuincendio.setBackground(new java.awt.Color(255, 51, 51));
        btm_docuincendio.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btm_docuincendio.setForeground(new java.awt.Color(255, 255, 255));
        btm_docuincendio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/incendio(1).png"))); // NOI18N
        btm_docuincendio.setText("¿Qué hacer en un incendio?");
        btm_docuincendio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        btm_docuincendio.setIconTextGap(10);
        btm_docuincendio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docuincendioActionPerformed(evt);
            }
        });

        btm_docuemergencia.setBackground(new java.awt.Color(255, 51, 51));
        btm_docuemergencia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btm_docuemergencia.setForeground(new java.awt.Color(255, 255, 255));
        btm_docuemergencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/emergenciamedica(1).jpg"))); // NOI18N
        btm_docuemergencia.setText("¿Que hacer en una emergencia?");
        btm_docuemergencia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        btm_docuemergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docuemergenciaActionPerformed(evt);
            }
        });

        btm_docuasalto.setBackground(new java.awt.Color(255, 51, 51));
        btm_docuasalto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btm_docuasalto.setForeground(new java.awt.Color(255, 255, 255));
        btm_docuasalto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/asalto (2).png"))); // NOI18N
        btm_docuasalto.setText("¿Qué hacer en un asalto?");
        btm_docuasalto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        btm_docuasalto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btm_docuasalto.setIconTextGap(10);
        btm_docuasalto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docuasaltoActionPerformed(evt);
            }
        });

        btm_docuvolver.setBackground(new java.awt.Color(255, 0, 0));
        btm_docuvolver.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btm_docuvolver.setText("<");
        btm_docuvolver.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btm_docuvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_docuvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_apartadoLayout = new javax.swing.GroupLayout(panel_apartado);
        panel_apartado.setLayout(panel_apartadoLayout);
        panel_apartadoLayout.setHorizontalGroup(
            panel_apartadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btm_docuvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel_apartadoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbl_apartado))
            .addComponent(btm_docuincendio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel_apartadoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btm_docurobocasa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btm_docuprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btm_docuemergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btm_docuasalto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_apartadoLayout.setVerticalGroup(
            panel_apartadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_apartadoLayout.createSequentialGroup()
                .addComponent(btm_docuvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_apartado)
                .addGap(74, 74, 74)
                .addGroup(panel_apartadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_apartadoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btm_docuincendio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_apartadoLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btm_docurobocasa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btm_docuprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_apartadoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btm_docuemergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_apartadoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btm_docuasalto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_mensajeinicio.setBackground(new java.awt.Color(255, 51, 51));

        lbl_introdocu.setBackground(new java.awt.Color(255, 51, 51));
        lbl_introdocu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_introdocu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_introdocu.setText("Documentación de Ayuda");

        dateText.setBackground(new java.awt.Color(255, 51, 51));
        dateText.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {name}{day} de {month} de {year}");

        javax.swing.GroupLayout panel_mensajeinicioLayout = new javax.swing.GroupLayout(panel_mensajeinicio);
        panel_mensajeinicio.setLayout(panel_mensajeinicioLayout);
        panel_mensajeinicioLayout.setHorizontalGroup(
            panel_mensajeinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mensajeinicioLayout.createSequentialGroup()
                .addGroup(panel_mensajeinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mensajeinicioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_introdocu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mensajeinicioLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(dateText)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        panel_mensajeinicioLayout.setVerticalGroup(
            panel_mensajeinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mensajeinicioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_introdocu)
                .addGap(18, 18, 18)
                .addComponent(dateText))
        );

        content.setPreferredSize(new java.awt.Dimension(542, 444));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_backgroundLayout = new javax.swing.GroupLayout(panel_background);
        panel_background.setLayout(panel_backgroundLayout);
        panel_backgroundLayout.setHorizontalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_apartado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_mensajeinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel_backgroundLayout.setVerticalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_apartado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_mensajeinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_docurobocasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docurobocasaActionPerformed
        ShowJPanel(new robodecasa());
    }//GEN-LAST:event_btm_docurobocasaActionPerformed

    private void btm_docuprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docuprincipalActionPerformed
        ShowJPanel(new Principal());
    }//GEN-LAST:event_btm_docuprincipalActionPerformed

    private void btm_docuincendioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docuincendioActionPerformed
        ShowJPanel(new incendio());
    }//GEN-LAST:event_btm_docuincendioActionPerformed

    private void btm_docuemergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docuemergenciaActionPerformed
        ShowJPanel(new emergencia());
    }//GEN-LAST:event_btm_docuemergenciaActionPerformed

    private void btm_docuasaltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docuasaltoActionPerformed
        ShowJPanel(new Asalto());
    }//GEN-LAST:event_btm_docuasaltoActionPerformed

    private void btm_docuvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_docuvolverActionPerformed
        this.setVisible(false);
        MenúPrincipalAlarma m= new MenúPrincipalAlarma();
        m.setVisible(true);
    }//GEN-LAST:event_btm_docuvolverActionPerformed

    private void InitContent(){
        ShowJPanel(new Principal());
    }
    
   public static void ShowJPanel(JPanel p) {
        p.setSize(542, 444);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    
    
    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentaciondeAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentaciondeAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentaciondeAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentaciondeAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DocumentaciondeAyuda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_docuasalto;
    private javax.swing.JButton btm_docuemergencia;
    private javax.swing.JButton btm_docuincendio;
    private static javax.swing.JButton btm_docuprincipal;
    private javax.swing.JButton btm_docurobocasa;
    private javax.swing.JButton btm_docuvolver;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel lbl_apartado;
    private javax.swing.JLabel lbl_introdocu;
    private javax.swing.JPanel panel_apartado;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_mensajeinicio;
    // End of variables declaration//GEN-END:variables
}
