/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameBotonAlerta;

/**
 *
 * @author Lenin
 */
public class HisorialAlertas extends javax.swing.JFrame {

    /**
     * Creates new form HisorialAlertas
     */
    public HisorialAlertas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        lbCalleAsalto = new javax.swing.JLabel();
        Asalto = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbCalleAsalto1 = new javax.swing.JLabel();
        lbCalleAsalto2 = new javax.swing.JLabel();
        lbUsuario1 = new javax.swing.JLabel();
        Asalto1 = new javax.swing.JLabel();
        Asalto2 = new javax.swing.JLabel();
        lbCalleAsalto3 = new javax.swing.JLabel();
        lbUsuario2 = new javax.swing.JLabel();
        Asalto3 = new javax.swing.JLabel();
        lbUsuario3 = new javax.swing.JLabel();
        Asalto4 = new javax.swing.JLabel();
        lbUsuario4 = new javax.swing.JLabel();
        lbCalleAsalto4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HISTORIAL DE ALERTAS");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Regreso.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbCalleAsalto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCalleAsalto.setForeground(new java.awt.Color(204, 204, 204));
        lbCalleAsalto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalleAsalto.setText("Calle1208");
        lbCalleAsalto.setFocusable(false);
        lbCalleAsalto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbCalleAsalto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 60, -1));

        Asalto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Asalto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asalto.setText("EMERGENCIA MEDICA");
        Asalto.setFocusable(false);
        Asalto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Asalto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, -1));

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario.setText("Usuario2");
        lbUsuario.setFocusable(false);
        lbUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 10));

        lbCalleAsalto1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCalleAsalto1.setForeground(new java.awt.Color(204, 204, 204));
        lbCalleAsalto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalleAsalto1.setText("Calle1208");
        lbCalleAsalto1.setFocusable(false);
        lbCalleAsalto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbCalleAsalto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, -1));

        lbCalleAsalto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCalleAsalto2.setForeground(new java.awt.Color(204, 204, 204));
        lbCalleAsalto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalleAsalto2.setText("Calle1208");
        lbCalleAsalto2.setFocusable(false);
        lbCalleAsalto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbCalleAsalto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, -1));

        lbUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario1.setText("Usuario2");
        lbUsuario1.setFocusable(false);
        lbUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, 10));

        Asalto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Asalto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asalto1.setText("ASALTO");
        Asalto1.setFocusable(false);
        Asalto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Asalto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        Asalto2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Asalto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asalto2.setText("INCENDIO");
        Asalto2.setFocusable(false);
        Asalto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Asalto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, -1));

        lbCalleAsalto3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCalleAsalto3.setForeground(new java.awt.Color(204, 204, 204));
        lbCalleAsalto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalleAsalto3.setText("Calle1208");
        lbCalleAsalto3.setFocusable(false);
        lbCalleAsalto3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbCalleAsalto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, -1));

        lbUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario2.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario2.setText("Usuario2");
        lbUsuario2.setFocusable(false);
        lbUsuario2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 10));

        Asalto3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Asalto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asalto3.setText("ROBO DE CASA");
        Asalto3.setFocusable(false);
        Asalto3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Asalto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbUsuario3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario3.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario3.setText("Usuario2");
        lbUsuario3.setFocusable(false);
        lbUsuario3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 10));

        Asalto4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Asalto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Asalto4.setText("PERSONA SOSPECHOSA");
        Asalto4.setFocusable(false);
        Asalto4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Asalto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        lbUsuario4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario4.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario4.setText("Usuario2");
        lbUsuario4.setFocusable(false);
        lbUsuario4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, -1));

        lbCalleAsalto4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCalleAsalto4.setForeground(new java.awt.Color(204, 204, 204));
        lbCalleAsalto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalleAsalto4.setText("Calle1208");
        lbCalleAsalto4.setFocusable(false);
        lbCalleAsalto4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbCalleAsalto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Icon.Incendio.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Icon.Asalto.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Icon.RoboCasa.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Icon.Sopechoso.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrameBotonAlerta/Imagenes/Icon.Hospital.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HisorialAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HisorialAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HisorialAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HisorialAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HisorialAlertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asalto;
    private javax.swing.JLabel Asalto1;
    private javax.swing.JLabel Asalto2;
    private javax.swing.JLabel Asalto3;
    private javax.swing.JLabel Asalto4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCalleAsalto;
    private javax.swing.JLabel lbCalleAsalto1;
    private javax.swing.JLabel lbCalleAsalto2;
    private javax.swing.JLabel lbCalleAsalto3;
    private javax.swing.JLabel lbCalleAsalto4;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuario1;
    private javax.swing.JLabel lbUsuario2;
    private javax.swing.JLabel lbUsuario3;
    private javax.swing.JLabel lbUsuario4;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
